import type { Lead, StageId, Task } from "./types";

export const stages: Array<{ id: StageId; label: string; probability: number }> = [
  { id: "new", label: "Novo lead", probability: 15 },
  { id: "qualified", label: "Qualificado", probability: 35 },
  { id: "proposal", label: "Proposta", probability: 60 },
  { id: "negotiation", label: "Negociação", probability: 80 },
  { id: "won", label: "Fechado", probability: 100 },
];

export const initialLeads: Lead[] = [
  {
    id: "lead-001",
    company: "Clínica Atlântico",
    contact: "Marta Nunes",
    email: "marta@clinicaatlantico.pt",
    phone: "+351 912 345 610",
    value: 6200,
    probability: 60,
    stage: "proposal",
    source: "Referência",
    owner: "Roberto",
    city: "Funchal",
    nextStep: "Enviar proposta final com módulo de faturação",
    dueDate: "2026-05-28",
    lastActivity: "Reunião de descoberta concluída",
    tags: ["Saúde", "Marcações", "PME"],
  },
  {
    id: "lead-002",
    company: "Madeira Homes",
    contact: "Tiago Sá",
    email: "tiago@madeirahomes.pt",
    phone: "+351 965 222 118",
    value: 9800,
    probability: 80,
    stage: "negotiation",
    source: "Website",
    owner: "Roberto",
    city: "Funchal",
    nextStep: "Validar calendário de implementação",
    dueDate: "2026-05-29",
    lastActivity: "Cliente pediu faseamento em 2 entregas",
    tags: ["Imobiliário", "Portal", "Automação"],
  },
  {
    id: "lead-003",
    company: "Oficina Central",
    contact: "Hugo Ferreira",
    email: "geral@oficinacentral.pt",
    phone: "+351 291 400 122",
    value: 3800,
    probability: 35,
    stage: "qualified",
    source: "LinkedIn",
    owner: "Inês",
    city: "Câmara de Lobos",
    nextStep: "Marcar demonstração de agenda e avisos SMS",
    dueDate: "2026-05-30",
    lastActivity: "Lead qualificado por telefone",
    tags: ["Serviços", "Agenda"],
  },
  {
    id: "lead-004",
    company: "Contas & Gestão",
    contact: "Rui Abreu",
    email: "rui@contasegestao.pt",
    phone: "+351 962 908 774",
    value: 7200,
    probability: 15,
    stage: "new",
    source: "Campanha",
    owner: "Roberto",
    city: "Lisboa",
    nextStep: "Enviar email de apresentação",
    dueDate: "2026-05-27",
    lastActivity: "Formulário submetido no website",
    tags: ["Contabilidade", "Dashboard"],
  },
  {
    id: "lead-005",
    company: "Solar Norte",
    contact: "Carla Mateus",
    email: "carla@solarnorte.pt",
    phone: "+351 934 780 201",
    value: 12400,
    probability: 80,
    stage: "negotiation",
    source: "Evento",
    owner: "Inês",
    city: "Porto",
    nextStep: "Rever integrações com ERP",
    dueDate: "2026-06-01",
    lastActivity: "Proposta técnica revista",
    tags: ["Energia", "ERP", "B2B"],
  },
  {
    id: "lead-006",
    company: "Restaurante Baía",
    contact: "Pedro Freitas",
    email: "pedro@baia.pt",
    phone: "+351 919 600 441",
    value: 2600,
    probability: 35,
    stage: "qualified",
    source: "Referência",
    owner: "Roberto",
    city: "Machico",
    nextStep: "Preparar proposta para reservas e vouchers",
    dueDate: "2026-05-31",
    lastActivity: "Pedido recebido via parceiro",
    tags: ["Restauração", "Reservas"],
  },
  {
    id: "lead-007",
    company: "FormaPro Academy",
    contact: "Sofia Lima",
    email: "sofia@formapro.pt",
    phone: "+351 915 041 882",
    value: 5600,
    probability: 60,
    stage: "proposal",
    source: "Website",
    owner: "Inês",
    city: "Braga",
    nextStep: "Apresentar área de aluno e pagamentos",
    dueDate: "2026-06-03",
    lastActivity: "Demonstração enviada",
    tags: ["Educação", "Portal"],
  },
  {
    id: "lead-008",
    company: "Vila Verde Tours",
    contact: "Miguel Sousa",
    email: "miguel@vilaverdetours.pt",
    phone: "+351 963 111 409",
    value: 4100,
    probability: 100,
    stage: "won",
    source: "Referência",
    owner: "Roberto",
    city: "Santana",
    nextStep: "Enviar contrato e fatura inicial",
    dueDate: "2026-05-27",
    lastActivity: "Negócio fechado",
    tags: ["Turismo", "Reservas"],
  },
];

export const initialTasks: Task[] = [
  {
    id: "task-001",
    leadId: "lead-004",
    title: "Enviar email de apresentação",
    due: "Hoje, 10:30",
    type: "Email",
    done: false,
  },
  {
    id: "task-002",
    leadId: "lead-001",
    title: "Fechar proposta com módulo de faturação",
    due: "Hoje, 15:00",
    type: "Proposta",
    done: false,
  },
  {
    id: "task-003",
    leadId: "lead-002",
    title: "Confirmar calendário de implementação",
    due: "Amanhã, 09:15",
    type: "Chamada",
    done: false,
  },
  {
    id: "task-004",
    leadId: "lead-006",
    title: "Marcar reunião de demonstração",
    due: "Sexta, 11:00",
    type: "Reunião",
    done: true,
  },
];
